version: "3.5"

x-kafka-common:
  &kafka-common
  image: bitnami/kafka:3.7
  depends_on:
  - zookeeper
  environment:
    &kafka-common-env
    KAFKA_ENABLE_KRAFT: no
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ALLOW_PLAINTEXT_LISTENER: yes
    KAFKA_TLS_TYPE: PEM
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:SSL,EXTERNAL:SSL,PLAINTEXT:PLAINTEXT"
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    KAFKA_CFG_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    KAFKA_CERTIFICATE_PASSWORD: your-password
  networks:
    - proxynet

services:
 zookeeper:
   image: bitnami/zookeeper:3.7
   container_name: zookeeper
   restart: always
   ports:
     - "2181:2181"
   volumes:
     - zookeeper-data:/bitnami/zookeeper
   environment:
     ZOO_PORT_NUMBER: 2181
     ZOO_TICK_TIME: 2000
     ALLOW_ANONYMOUS_LOGIN: yes
   networks:
     - proxynet

 kafka-1:
   <<: *kafka-common
   container_name: kafka-1
   restart: always
   ports:
     - "9094:9094"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 1
     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,EXTERNAL://kafka-1:9094
   volumes:
     - kafka_1_data:/bitnami/kafka
     - ./ssl/kafka-1-creds/kafka-1.crt:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro
     - ./ssl/kafka-1-creds/kafka-1.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro
     - ./ssl/ca.crt:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro
     - ./client.config:/client.config:ro

 kafka-2:
   <<: *kafka-common
   container_name: kafka-2
   restart: always
   ports:
     - "9095:9095"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 2
     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9095
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,EXTERNAL://kafka-2:9095
   volumes:
     - kafka_2_data:/bitnami/kafka
     - ./ssl/kafka-2-creds/kafka-2.crt:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro
     - ./ssl/kafka-2-creds/kafka-2.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro
     - ./ssl/ca.crt:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro

 kafka-3:
   <<: *kafka-common
   container_name: kafka-3
   restart: always
   ports:
     - "9096:9096"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 3
     KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9096
     KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,EXTERNAL://kafka-3:9096
   volumes:
     - kafka_3_data:/bitnami/kafka
     - ./ssl/kafka-3-creds/kafka-3.crt:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro
     - ./ssl/kafka-3-creds/kafka-3.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro
     - ./ssl/ca.crt:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro

 ui:
   image: provectuslabs/kafka-ui:v0.7.0
   restart: always
   ports:
     - "127.0.0.1:8086:8080"
   environment:
     KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-1:9092,kafka-2:9092,kafka-3:9092
     KAFKA_CLUSTERS_0_NAME: zoo
   networks:
     - proxynet

networks:
 proxynet:
   name: custom_network

volumes:
 kafka_1_data:
 kafka_2_data:
 kafka_3_data: 
 zookeeper-data: