version: "3.5"

x-kafka-common:
  &kafka-common
  image: bitnami/kafka:3.9
  depends_on:
  - zookeeper
  environment:
    &kafka-common-env
    BITNAMI_DEBUG: 'true'
    KAFKA_HEAP_OPTS: -Djavax.net.debug=ssl
    KAFKA_ENABLE_KRAFT: no
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ALLOW_PLAINTEXT_LISTENER: yes
    KAFKA_TLS_TYPE: JKS
    KAFKA_CFG_SECURITY_PROTOCOL: "SASL_SSL"
    KAFKA_CFG_SSL_KEYSTORE_TYPE: JKS
    KAFKA_CFG_SSL_TRUSTSTORE_TYPE: JKS
    KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:SASL_SSL,EXTERNAL:SASL_SSL,INTERNAL:SASL_SSL"
    KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
    KAFKA_TLS_CLIENT_AUTH: 'requested'
    KAFKA_CERTIFICATE_PASSWORD: your-password
    KAFKA_CFG_LISTENER_NAME_EXTERNAL_PLAIN_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret" user_consumer="consumer-secret" user_producer="producer-secret";'
    KAFKA_CFG_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
    KAFKA_CFG_SUPER_USERS: 'User:user;User:controller_user;User:admin'
    KAFKA_CFG_SASL_ENABLED_MECHANISMS: 'PLAIN'
    KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: 'PLAIN'
    KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: 'PLAIN'
    KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  networks:
    - proxynet

services:
 zookeeper:
   image: bitnami/zookeeper:3.9
   container_name: zookeeper
   restart: always
   ports:
     - "2181:2181"
   volumes:
     - zookeeper-data:/bitnami/zookeeper
   environment:
     ZOO_PORT_NUMBER: 2181
     ZOO_TICK_TIME: 2000
     ALLOW_ANONYMOUS_LOGIN: yes
   networks:
     - proxynet

 kafka-1:
   <<: *kafka-common
   container_name: kafka-1
   restart: always
   ports:
     - "9094:9094"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 1
     KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
     KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://kafka-1:9094
   volumes:
     - kafka_1_data:/bitnami/kafka
     - ./ssl/kafka-1-creds/kafka.kafka-1.keystore.pkcs12:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
     - ./ssl/kafka-1-creds/kafka.kafka-1.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro
     - ./admin-config.conf:/admin-config.conf:ro

 kafka-2:
   <<: *kafka-common
   container_name: kafka-2
   restart: always
   ports:
     - "9095:9095"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 2
     KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9095
     KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://kafka-2:9095
   volumes:
     - kafka_2_data:/bitnami/kafka
     - ./ssl/kafka-2-creds/kafka.kafka-2.keystore.pkcs12:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
     - ./ssl/kafka-2-creds/kafka.kafka-2.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

 kafka-3:
   <<: *kafka-common
   container_name: kafka-3
   restart: always
   ports:
     - "9096:9096"
   environment:
     <<: *kafka-common-env
     KAFKA_CFG_NODE_ID: 3
     KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9096
     KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-3:9092,EXTERNAL://kafka-3:9096
   volumes:
     - kafka_3_data:/bitnami/kafka
     - ./ssl/kafka-3-creds/kafka.kafka-3.keystore.pkcs12:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro
     - ./ssl/kafka-3-creds/kafka.kafka-3.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro

 ui:
   image: provectuslabs/kafka-ui:v0.7.0
   restart: always
   ports:
     - "127.0.0.1:8086:8080"
   environment:
     KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-1:9094,kafka-2:9095,kafka-3:9096
     KAFKA_CLUSTERS_0_NAME: zoo
     KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: "SASL_SSL"
     KAFKA_CLUSTERS_0_SSL_TRUSTSTORELOCATION: "/kafka.kafka-1.truststore.jks"
     KAFKA_CLUSTERS_0_SSL_TRUSTSTOREPASSWORD: "your-password"
     KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
     KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";'
   volumes:
    - ./ssl/kafka-1-creds/kafka.kafka-1.truststore.jks:/kafka.kafka-1.truststore.jks:ro
   networks:
     - proxynet

 schema-registry:
    image: bitnami/schema-registry:7.9.0
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
    ports:
      - "8081:8081"
    environment:
      - BITNAMI_DEBUG=true
      - SCHEMA_REGISTRY_KAFKA_BROKERS=SASL_SSL://kafka-1:9094,SASL_SSL://kafka-2:9095,SASL_SSL://kafka-3:9096
      - SCHEMA_REGISTRY_KAFKA_SASL_USER=admin
      - SCHEMA_REGISTRY_KAFKA_SASL_PASSWORD=admin-secret
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_KAFKA_TRUSTSTORE_PASSWORD=your-password
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    volumes:
      - ./ssl/kafka-1-creds/kafka.kafka-1.truststore.jks:/opt/bitnami/schema-registry/certs/schema-registry.truststore.jks:ro
    networks:
      - proxynet

 producer:
    build: 
      context: producer
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    ports:
      - "9000:9000"
    environment:
      - PRODUCER_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9094,kafka-2:9095,kafka-3:9096
      - PRODUCER_SCHEMA_REGISTRY_SERVER=http://schema-registry:8081
      - PRODUCER_KAFKA_TOPIC=topic-1
      - PRODUCER_KAFKA_USER=producer
      - PRODUCER_KAFKA_PASSWORD=producer-secret
      - PRODUCER_KAFKA_CA_PATH=/ca.crt
    networks:
      - proxynet
    volumes:
      - ./ssl/ca.crt:/ca.crt:ro

 consumer:
    build: 
      context: consumer
    depends_on:
      - kafka-1
      - kafka-2
      - kafka-3
      - schema-registry
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - CONSUMER_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9094,kafka-2:9095,kafka-3:9096
      - CONSUMER_SCHEMA_REGISTRY_SERVER=http://schema-registry:8081
      - CONSUMER_KAFKA_TOPIC=topic-1
      - CONSUMER_GROUP_ID=single-group
      - CONSUMER_MESSAGES_BATCH_MIN=1
      - CONSUMER_MESSAGES_BATCH_MAX=1
      - CONSUMER_AUTO_COMMIT=true
      - CONSUMER_POLL_INTERVAL_SECONDS=10
      - CONSUMER_KAFKA_USER=consumer
      - CONSUMER_KAFKA_PASSWORD=consumer-secret
      - CONSUMER_KAFKA_CA_PATH=/ca.crt
    networks:
      - proxynet
    volumes:
      - ./ssl/ca.crt:/ca.crt:ro

networks:
 proxynet:
   name: custom_network

volumes:
 kafka_1_data:
 kafka_2_data:
 kafka_3_data: 
 zookeeper-data: